name: 'QA check with pkgcheck'
on: [push, pull_request]
jobs:
    repoman:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: pkgcore/pkgcheck-action@v1
              with:
                args: --exit=error,warning --keywords=-UnstableOnly,-PotentialStable,-RedundantLongDescription,-PythonCompatUpdate,-MissingRemoteId,-MissingTestRestrict,-PkgMetadataXmlEmptyElement,-UnnecessarySlashStrip,-VisibleVcsPkg,-MissingLocalUseDesc,-UnusedLocalUse,-ExcessiveLineLength,-UnusedProfileDirs
